
import React from 'react';
import { Download, RotateCcw, Heart, Copy } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { useToast } from '@/hooks/use-toast';

interface GeneratedAd {
  id: number;
  image: string;
  tagline: string;
  concept: string;
}

interface GeneratedAdsSectionProps {
  ads: GeneratedAd[];
}

const GeneratedAdsSection = ({ ads }: GeneratedAdsSectionProps) => {
  const { toast } = useToast();

  const handleSave = (ad: GeneratedAd) => {
    toast({
      title: "Saved! 💖",
      description: "Added to your ad collection.",
    });
  };

  const handleCopyText = (tagline: string) => {
    navigator.clipboard.writeText(tagline);
    toast({
      title: "Copied! 📋",
      description: "Tagline copied to clipboard.",
    });
  };

  const handleDownload = (ad: GeneratedAd) => {
    toast({
      title: "Downloading! 📥",
      description: "Your silly ad is being downloaded.",
    });
  };

  return (
    <div className="space-y-6">
      <div className="text-center">
        <h2 className="text-3xl font-bold text-gray-900 mb-2">
          🎉 Your Silly Ads Are Ready!
        </h2>
        <p className="text-gray-600">
          Generated by AI, approved by chaos. Pick your favorite!
        </p>
      </div>

      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
        {ads.map((ad) => (
          <Card key={ad.id} className="group hover:shadow-xl transition-all duration-300 transform hover:-translate-y-1 bg-white border-2 border-transparent hover:border-teal-200">
            <CardContent className="p-0">
              {/* Image */}
              <div className="relative overflow-hidden rounded-t-lg">
                <img
                  src={ad.image}
                  alt="Generated ad"
                  className="w-full h-64 object-cover group-hover:scale-105 transition-transform duration-300"
                />
                <div className="absolute inset-0 bg-black bg-opacity-0 group-hover:bg-opacity-10 transition-all duration-300"></div>
              </div>

              {/* Content */}
              <div className="p-6 space-y-4">
                {/* Tagline */}
                <div className="bg-gradient-to-r from-yellow-100 to-orange-100 p-4 rounded-lg border-l-4 border-yellow-400">
                  <p className="font-bold text-gray-900 text-lg leading-relaxed">
                    "{ad.tagline}"
                  </p>
                </div>

                {/* Concept */}
                <p className="text-sm text-gray-600 italic bg-gray-50 p-3 rounded-lg">
                  {ad.concept}
                </p>

                {/* Action Buttons */}
                <div className="grid grid-cols-2 gap-2">
                  <Button
                    onClick={() => handleDownload(ad)}
                    variant="outline"
                    size="sm"
                    className="flex items-center space-x-1 hover:bg-green-50 hover:border-green-300"
                  >
                    <Download className="w-4 h-4" />
                    <span>Download</span>
                  </Button>

                  <Button
                    onClick={() => handleSave(ad)}
                    variant="outline"
                    size="sm"
                    className="flex items-center space-x-1 hover:bg-pink-50 hover:border-pink-300"
                  >
                    <Heart className="w-4 h-4" />
                    <span>Save</span>
                  </Button>

                  <Button
                    onClick={() => handleCopyText(ad.tagline)}
                    variant="outline"
                    size="sm"
                    className="flex items-center space-x-1 hover:bg-blue-50 hover:border-blue-300"
                  >
                    <Copy className="w-4 h-4" />
                    <span>Copy Text</span>
                  </Button>

                  <Button
                    variant="outline"
                    size="sm"
                    className="flex items-center space-x-1 hover:bg-purple-50 hover:border-purple-300"
                  >
                    <RotateCcw className="w-4 h-4" />
                    <span>Re-gen</span>
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Generate More Button */}
      <div className="text-center pt-6">
        <Button className="bg-gradient-to-r from-teal-500 to-blue-500 hover:from-teal-600 hover:to-blue-600 text-white font-semibold px-8 py-3 rounded-full">
          🎨 Generate More Variations
        </Button>
      </div>
    </div>
  );
};

export default GeneratedAdsSection;
