// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ioardkeakraewibwlqwq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlvYXJka2Vha3JhZXdpYndscXdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NzUxMTksImV4cCI6MjA2NTI1MTExOX0.43JWRDVlN0TUrYm_bmYGnNCANtdz7c5n1xuYuJCXtm0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);